
["Particle Effects"]
	#Flame particles on Ashenwheat crop?
	MakeAshenwheatFlame = true
	#Flame and smoke particles on Ashenwheat bales?
	MakeAshenBalesFlame = true
	#Scintillating particles on Scintillawheat crop?
	MakeScintillawheatScintillate = true
	#Scintillating particles on Scintillawheat bales?
	MakeScintillaBalesScintillate = true
	#Like scintillations, but not quite so much?
	MakeScintillationsSmaller = false
	#Gloom particles on Ossidroot crop?
	MakeOssidCropGloom = true
	#Gloom particles on Ossidroots, Carved Ossidroots, and Ossidroot Lanterns?
	MakeOssidLanternGloom = true
	#A developer of this mod has defined this config option with a blank comment, which causes obscure bugs in Forge's config system and will cause a crash in the future. Please report this to the mod author.
	MakeThunderGrassSmoke = true
	#Want smoke, but not that much?
	MakeThunderGrassSmokeSmaller = false

